//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suraj3.Db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "The Name is Field")]
        public string Name { get; set; }
        [Required(ErrorMessage = "The Email is Field")]
        public string Email { get; set; }
        [Required(ErrorMessage = "The Addredd is Field")]
        public string Address { get; set; }
    }
}
